# Generated by Django 2.1.4 on 2018-12-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_orig_config',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type_name',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
