# Generated by Django 2.1.4 on 2018-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcmgmt', '0002_auto_20181226_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='object_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='resource_count',
            field=models.IntegerField(default=0),
        ),
    ]
