# Generated by Django 2.1.4 on 2018-12-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcmgmt', '0003_auto_20181227_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=15)),
                ('edc_version', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('security_domain', models.CharField(max_length=50)),
                ('resource_count', models.IntegerField(default=0)),
                ('object_count', models.IntegerField(default=0)),
                ('custom_attr_count', models.IntegerField(default=0)),
            ],
        ),
    ]
