# Generated by Django 2.1.4 on 2019-01-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcmgmt', '0005_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='attr_id',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
