# Generated by Django 2.1.4 on 2019-01-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcmgmt', '0007_attributes_attr_orig_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='attr_env_version',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_env_version',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
